import { Contact, CallRecord } from "./types";
import { normalizePhone } from "./utils";

const rawContacts: Contact[] = [
  {
    id: "c-001",
    salutation: "Herr",
    firstName: "Markus",
    lastName: "Schneider",
    phone: "+49 172 3456789",
    phoneMobile: "+49 172 3456789",
    email: "m.schneider@techwerk.de",
    company: "TechWerk GmbH",
    position: "Geschaeftsfuehrer",
    department: "Management",
    street: "Hauptstr. 42",
    zip: "80331",
    city: "Muenchen",
    country: "Deutschland",
    callReason: "Interesse an unserer KI-Telefonloesung fuer den Kundenservice gezeigt. Hat auf der Messe einen Flyer mitgenommen und moechte ein Demo-Gespraech vereinbaren.",
    preferredCallTime: "Vormittags 9-12 Uhr",
    language: "Deutsch",
    notes: "Sehr technikaffin, will Details zur API-Integration",
    tags: ["lead", "enterprise"],
    source: "Messe",
    status: "new",
    createdAt: "2026-03-01T09:00:00Z",
    updatedAt: "2026-03-01T09:00:00Z",
  },
  {
    id: "c-002",
    salutation: "Frau",
    title: "Dr.",
    firstName: "Sabine",
    lastName: "Mueller",
    phone: "+49 30 9876543",
    email: "s.mueller@berlinmed.de",
    company: "Berlin Medizintechnik AG",
    position: "Leiterin IT",
    department: "IT",
    street: "Friedrichstr. 110",
    zip: "10117",
    city: "Berlin",
    country: "Deutschland",
    callReason: "Bestehende Kundin, Vertrag laeuft in 2 Monaten aus. Verlaengerung besprechen und Upselling auf Premium-Paket.",
    preferredCallTime: "Nachmittags 14-17 Uhr",
    language: "Deutsch",
    tags: ["bestandskunde", "upselling"],
    source: "CRM",
    status: "contacted",
    lastContactDate: "2026-02-20T14:30:00Z",
    createdAt: "2025-11-15T10:00:00Z",
    updatedAt: "2026-02-20T14:30:00Z",
  },
  {
    id: "c-003",
    salutation: "Herr",
    firstName: "Thomas",
    lastName: "Weber",
    phone: "+49 151 22334455",
    email: "t.weber@autohausweber.de",
    company: "Autohaus Weber",
    position: "Inhaber",
    street: "Industriestr. 7",
    zip: "70174",
    city: "Stuttgart",
    country: "Deutschland",
    callReason: "Rueckruf angefordert nach Online-Anfrage. Sucht Loesung fuer automatisierte Terminvereinbarung im Autohaus.",
    language: "Deutsch",
    tags: ["lead", "callback"],
    source: "Webformular",
    status: "callback",
    lastContactDate: "2026-02-28T11:00:00Z",
    createdAt: "2026-02-28T11:00:00Z",
    updatedAt: "2026-02-28T11:00:00Z",
  },
  {
    id: "c-004",
    salutation: "Frau",
    firstName: "Lisa",
    lastName: "Hoffmann",
    phone: "+49 176 55667788",
    email: "l.hoffmann@versicherungplus.de",
    company: "VersicherungPlus",
    position: "Vertriebsleiterin",
    department: "Vertrieb",
    street: "Koenigsallee 23",
    zip: "40212",
    city: "Duesseldorf",
    country: "Deutschland",
    callReason: "Moechte unsere Outbound-Calling-Loesung fuer die Kaltakquise testen. Budget von 50k/Jahr vorhanden.",
    preferredCallTime: "Dienstag und Donnerstag",
    language: "Deutsch",
    notes: "Sehr interessiert, Entscheidungstraegerin",
    tags: ["hot-lead", "enterprise"],
    source: "LinkedIn",
    status: "scheduled",
    nextScheduledCall: "2026-03-06T10:00:00Z",
    createdAt: "2026-02-25T08:00:00Z",
    updatedAt: "2026-03-01T16:00:00Z",
  },
  {
    id: "c-005",
    salutation: "Herr",
    firstName: "Andreas",
    lastName: "Fischer",
    phone: "+49 162 11223344",
    email: "a.fischer@handwerkerportal.de",
    company: "HandwerkerPortal24",
    position: "CTO",
    department: "Technik",
    street: "Bergstr. 5",
    zip: "50667",
    city: "Koeln",
    country: "Deutschland",
    callReason: "Technische Evaluierung unserer API. Will wissen ob Integration mit ihrem bestehenden CRM (Salesforce) moeglich ist.",
    language: "Deutsch",
    tags: ["lead", "technical"],
    source: "Empfehlung",
    status: "contacted",
    lastContactDate: "2026-03-02T09:30:00Z",
    createdAt: "2026-02-18T12:00:00Z",
    updatedAt: "2026-03-02T09:30:00Z",
  },
  {
    id: "c-006",
    salutation: "Frau",
    firstName: "Julia",
    lastName: "Becker",
    phone: "+49 170 99887766",
    email: "j.becker@reisebuero-sonnenschein.de",
    company: "Reisebuero Sonnenschein",
    position: "Inhaberin",
    street: "Marktplatz 3",
    zip: "60311",
    city: "Frankfurt",
    country: "Deutschland",
    callReason: "Kleines Reisebuero, sucht automatisierte Buchungsbestaetigung und Follow-up Anrufe nach Reisen.",
    language: "Deutsch",
    tags: ["lead", "smb"],
    source: "Google Ads",
    status: "new",
    createdAt: "2026-03-03T14:00:00Z",
    updatedAt: "2026-03-03T14:00:00Z",
  },
  {
    id: "c-007",
    salutation: "Herr",
    title: "Prof.",
    firstName: "Klaus",
    lastName: "Wagner",
    phone: "+49 152 44556677",
    email: "k.wagner@uni-hamburg.de",
    company: "Universitaet Hamburg",
    position: "Lehrstuhlinhaber KI",
    department: "Informatik",
    street: "Rothenbaumchaussee 36",
    zip: "20148",
    city: "Hamburg",
    country: "Deutschland",
    callReason: "Forschungskooperation. Moechte unsere Technologie in einem Forschungsprojekt einsetzen. Potenzielle Referenz.",
    language: "Deutsch",
    notes: "Akademischer Kontakt, langfristige Partnerschaft",
    tags: ["research", "partnership"],
    source: "Konferenz",
    status: "contacted",
    lastContactDate: "2026-02-15T16:00:00Z",
    createdAt: "2026-02-10T10:00:00Z",
    updatedAt: "2026-02-15T16:00:00Z",
  },
  {
    id: "c-008",
    salutation: "Frau",
    firstName: "Nina",
    lastName: "Schulz",
    phone: "+49 171 33445566",
    email: "n.schulz@immoscout.de",
    company: "ImmoScout Sued GmbH",
    position: "Head of Customer Success",
    department: "Customer Success",
    street: "Leopoldstr. 80",
    zip: "80802",
    city: "Muenchen",
    country: "Deutschland",
    callReason: "Braucht eine Loesung fuer Nachfass-Anrufe bei Immobilien-Interessenten. Bis zu 500 Anrufe pro Tag.",
    preferredCallTime: "Montag bis Mittwoch",
    language: "Deutsch",
    tags: ["hot-lead", "high-volume"],
    source: "Empfehlung",
    status: "new",
    createdAt: "2026-03-04T08:00:00Z",
    updatedAt: "2026-03-04T08:00:00Z",
  },
  {
    id: "c-009",
    salutation: "Herr",
    firstName: "Peter",
    lastName: "Koch",
    phone: "+49 163 77889900",
    email: "p.koch@energieberatung-koch.de",
    company: "Energieberatung Koch",
    position: "Berater",
    street: "Waldweg 12",
    zip: "90402",
    city: "Nuernberg",
    country: "Deutschland",
    callReason: "Einmann-Betrieb, sucht eine Loesung die Anrufe entgegennimmt wenn er im Aussendienst ist. Inbound-Fokus.",
    language: "Deutsch",
    tags: ["lead", "smb", "inbound"],
    source: "Webformular",
    status: "no-answer",
    lastContactDate: "2026-03-01T10:00:00Z",
    createdAt: "2026-02-27T09:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "c-010",
    salutation: "Frau",
    firstName: "Martina",
    lastName: "Braun",
    phone: "+49 157 12345678",
    email: "m.braun@stadtwerke-leipzig.de",
    company: "Stadtwerke Leipzig",
    position: "Abteilungsleiterin Kundenservice",
    department: "Kundenservice",
    street: "Augustusplatz 1",
    zip: "04109",
    city: "Leipzig",
    country: "Deutschland",
    callReason: "Oeffentlicher Versorger sucht Automatisierung fuer Zaehlerstands-Abfragen und Stoerungsmeldungen.",
    language: "Deutsch",
    notes: "Vergabeverfahren, braucht Referenzen",
    tags: ["enterprise", "public-sector"],
    source: "Ausschreibung",
    status: "scheduled",
    nextScheduledCall: "2026-03-07T11:00:00Z",
    createdAt: "2026-02-20T08:00:00Z",
    updatedAt: "2026-03-03T14:00:00Z",
  },
  {
    id: "c-011",
    salutation: "Herr",
    firstName: "Stefan",
    lastName: "Richter",
    phone: "+49 175 66778899",
    email: "s.richter@logistikpro.de",
    company: "LogistikPro GmbH",
    position: "Operations Manager",
    department: "Operations",
    street: "Hafenstr. 25",
    zip: "28195",
    city: "Bremen",
    country: "Deutschland",
    callReason: "Moechte Fahrer-Benachrichtigungen und Kunden-Updates automatisieren. Ca. 200 Anrufe taeglich.",
    language: "Deutsch",
    tags: ["lead", "mid-market"],
    source: "Messe",
    status: "new",
    createdAt: "2026-03-02T11:00:00Z",
    updatedAt: "2026-03-02T11:00:00Z",
  },
  {
    id: "c-012",
    salutation: "Frau",
    firstName: "Claudia",
    lastName: "Hartmann",
    phone: "+49 160 55443322",
    email: "c.hartmann@beauty-lounge.de",
    company: "Beauty Lounge Frankfurt",
    position: "Inhaberin",
    street: "Zeil 55",
    zip: "60313",
    city: "Frankfurt",
    country: "Deutschland",
    callReason: "Sucht automatische Terminbestaetigung und Erinnerungsanrufe fuer Kosmetik-Termine. Ca. 30 Termine/Tag.",
    language: "Deutsch",
    tags: ["lead", "smb"],
    source: "Instagram",
    status: "completed",
    lastContactDate: "2026-02-25T15:00:00Z",
    createdAt: "2026-02-10T09:00:00Z",
    updatedAt: "2026-02-25T15:00:00Z",
  },
  {
    id: "c-013",
    salutation: "Herr",
    firstName: "Michael",
    lastName: "Zimmermann",
    phone: "+49 179 88776655",
    email: "m.zimmermann@finanzhaus.de",
    company: "Finanzhaus Zimmermann",
    position: "Geschaeftsfuehrender Gesellschafter",
    street: "Bankstr. 8",
    zip: "30159",
    city: "Hannover",
    country: "Deutschland",
    callReason: "Finanzberatung mit 15 Beratern. Braucht Terminvereinbarung und Qualifizierung von Leads per Telefon.",
    preferredCallTime: "Ab 16 Uhr",
    language: "Deutsch",
    notes: "Hat bereits Konkurrenzprodukt im Einsatz, unzufrieden damit",
    tags: ["hot-lead", "competitor-switch"],
    source: "Empfehlung",
    status: "callback",
    lastContactDate: "2026-03-03T16:30:00Z",
    createdAt: "2026-02-22T10:00:00Z",
    updatedAt: "2026-03-03T16:30:00Z",
  },
  {
    id: "c-014",
    salutation: "Frau",
    firstName: "Sandra",
    lastName: "Krause",
    phone: "+49 174 22334455",
    email: "s.krause@pflege-mit-herz.de",
    company: "Pflege mit Herz",
    position: "Pflegedienstleitung",
    department: "Verwaltung",
    street: "Schillerstr. 19",
    zip: "01069",
    city: "Dresden",
    country: "Deutschland",
    callReason: "Pflegedienst sucht Loesung fuer Dienstplan-Aenderungen per Telefon an Mitarbeiter zu kommunizieren.",
    language: "Deutsch",
    tags: ["lead", "healthcare"],
    source: "Google Ads",
    status: "new",
    createdAt: "2026-03-04T10:00:00Z",
    updatedAt: "2026-03-04T10:00:00Z",
  },
  {
    id: "c-015",
    salutation: "Herr",
    firstName: "Joerg",
    lastName: "Schmitt",
    phone: "+49 168 99001122",
    email: "j.schmitt@gastro-koenig.de",
    company: "Gastro Koenig",
    position: "Betriebsleiter",
    street: "Am Markt 1",
    zip: "55116",
    city: "Mainz",
    country: "Deutschland",
    callReason: "Restaurantkette (5 Standorte) sucht automatische Reservierungsbestaetigung und Tischverfuegbarkeits-Auskunft.",
    language: "Deutsch",
    tags: ["lead", "gastro", "multi-location"],
    source: "Webformular",
    status: "contacted",
    lastContactDate: "2026-03-01T12:00:00Z",
    createdAt: "2026-02-26T14:00:00Z",
    updatedAt: "2026-03-01T12:00:00Z",
  },
  {
    id: "c-016",
    salutation: "Frau",
    firstName: "Katharina",
    lastName: "Lang",
    phone: "+49 155 33221100",
    email: "k.lang@startup-hub-berlin.de",
    company: "StartupHub Berlin",
    position: "Co-Founder & CEO",
    street: "Torstr. 75",
    zip: "10119",
    city: "Berlin",
    country: "Deutschland",
    callReason: "Tech-Startup Inkubator moechte Call-Agent-Loesung als White-Label fuer ihre Portfolio-Startups anbieten.",
    language: "Deutsch",
    notes: "Potenzielle Partnerschaft, grosses Volumen moeglich",
    tags: ["partnership", "white-label", "high-potential"],
    source: "LinkedIn",
    status: "scheduled",
    nextScheduledCall: "2026-03-05T14:00:00Z",
    createdAt: "2026-02-28T10:00:00Z",
    updatedAt: "2026-03-04T09:00:00Z",
  },
  {
    id: "c-017",
    salutation: "Herr",
    firstName: "Ralf",
    lastName: "Neumann",
    phone: "+49 177 44556600",
    email: "r.neumann@autoservice-neumann.de",
    company: "Autoservice Neumann",
    position: "Inhaber",
    street: "Werkstattweg 3",
    zip: "44135",
    city: "Dortmund",
    country: "Deutschland",
    callReason: "KFZ-Werkstatt moechte Kunden automatisch an Inspektionstermine und TUeV-Faelligkeit erinnern lassen.",
    language: "Deutsch",
    tags: ["lead", "smb", "automotive"],
    source: "Google Ads",
    status: "no-answer",
    lastContactDate: "2026-03-02T14:00:00Z",
    createdAt: "2026-02-24T11:00:00Z",
    updatedAt: "2026-03-02T14:00:00Z",
  },
];

// Normalize all phone numbers in sample contacts to storage format
export const sampleContacts: Contact[] = rawContacts.map((c) => ({
  ...c,
  phone: normalizePhone(c.phone),
  ...(c.phoneMobile ? { phoneMobile: normalizePhone(c.phoneMobile) } : {}),
}));

export const sampleCallRecords: CallRecord[] = [
  {
    id: "cr-001",
    contactId: "c-002",
    startedAt: "2026-02-20T14:30:00Z",
    endedAt: "2026-02-20T14:38:00Z",
    duration: 480,
    status: "completed",
    outcome: "answered",
    transcript: "Agent: Guten Tag Frau Dr. Mueller, hier spricht der CallAgent von TechCorp. Ich rufe an bezueglich Ihrer Vertragsverlaengerung.\nKundin: Ja, guten Tag. Ich habe den Brief erhalten.\nAgent: Wunderbar. Ihr aktueller Vertrag laeuft am 15. April aus. Wir wuerden Ihnen gerne unser neues Premium-Paket vorstellen.\nKundin: Das klingt interessant. Was beinhaltet das?\nAgent: Das Premium-Paket umfasst zusaetzlich KI-gestuetzte Anrufanalysen und Priority-Support. Soll ich Ihnen die Details per E-Mail senden?\nKundin: Ja, bitte. Und vereinbaren wir gleich einen Termin fuer naechste Woche.\nAgent: Sehr gerne. Wie waere Dienstag um 14 Uhr?\nKundin: Perfekt, das passt.",
    summary: "Vertragsverlaengerung besprochen. Kundin interessiert an Premium-Paket. Details per E-Mail. Folgetermin Dienstag 14 Uhr.",
    meetingBooked: true,
    meetingDate: "2026-02-25T14:00:00Z",
  },
  {
    id: "cr-002",
    contactId: "c-003",
    startedAt: "2026-02-28T11:00:00Z",
    endedAt: "2026-02-28T11:02:00Z",
    duration: 120,
    status: "completed",
    outcome: "callback-requested",
    summary: "Herr Weber war gerade in einem Meeting. Bittet um Rueckruf nach 15 Uhr.",
  },
  {
    id: "cr-003",
    contactId: "c-005",
    startedAt: "2026-03-02T09:30:00Z",
    endedAt: "2026-03-02T09:50:00Z",
    duration: 1200,
    status: "completed",
    outcome: "answered",
    transcript: "Agent: Guten Morgen Herr Fischer. Hier ist der CallAgent. Sie hatten Fragen zur Salesforce-Integration.\nKunde: Genau, wir nutzen Salesforce Enterprise und brauchen eine bidirektionale Sync.\nAgent: Das ist mit unserer API problemlos moeglich. Wir haben einen fertigen Salesforce-Connector.\nKunde: Sehr gut. Koennen Sie mir die technische Dokumentation schicken?\nAgent: Selbstverstaendlich. Ich schicke Ihnen den Link zur API-Doku und den Salesforce-Connector Guide.",
    summary: "Technische Fragen zur Salesforce-Integration beantwortet. API-Doku und Connector Guide per E-Mail gesendet.",
  },
  {
    id: "cr-004",
    contactId: "c-009",
    startedAt: "2026-03-01T10:00:00Z",
    endedAt: "2026-03-01T10:00:30Z",
    duration: 30,
    status: "completed",
    outcome: "no-answer",
    summary: "Keine Antwort. Mailbox nicht eingerichtet.",
  },
  {
    id: "cr-005",
    contactId: "c-012",
    startedAt: "2026-02-25T15:00:00Z",
    endedAt: "2026-02-25T15:12:00Z",
    duration: 720,
    status: "completed",
    outcome: "meeting-booked",
    summary: "Demo-Termin vereinbart fuer den 28. Februar. Inhaberin ist begeistert von der Loesung.",
    meetingBooked: true,
    meetingDate: "2026-02-28T10:00:00Z",
  },
  {
    id: "cr-006",
    contactId: "c-015",
    startedAt: "2026-03-01T12:00:00Z",
    endedAt: "2026-03-01T12:08:00Z",
    duration: 480,
    status: "completed",
    outcome: "answered",
    summary: "Erstkontakt mit Betriebsleiter. Interesse an Reservierungssystem. Wartet auf Angebot.",
  },
  {
    id: "cr-007",
    contactId: "c-013",
    startedAt: "2026-03-03T16:30:00Z",
    endedAt: "2026-03-03T16:35:00Z",
    duration: 300,
    status: "completed",
    outcome: "callback-requested",
    summary: "Herr Zimmermann moechte am Freitag nach 16 Uhr ausfuehrlich sprechen. Ist mit aktuellem Anbieter unzufrieden.",
  },
  {
    id: "cr-008",
    contactId: "c-017",
    startedAt: "2026-03-02T14:00:00Z",
    endedAt: "2026-03-02T14:00:25Z",
    duration: 25,
    status: "completed",
    outcome: "no-answer",
    summary: "Kein Abnehmer. Erneuter Versuch geplant.",
  },
];
